## Project information
site_name: Alma-Primo Locate Tool
site_url: https://leidenuniversitylibrary.github.io/Alma-Primo-Locate-Tool-Open-Source/
site_description: The open-source solution for guiding patrons to books in your open stacks

## Repository
repo_name: Alma-Primo Locate Tool
repo_url: https://github.com/LeidenUniversityLibrary/Alma-Primo-Locate-Tool-Open-Source
edit_uri: ''  #disables edit button

## Configuration

theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  custom_dir: docs/override/
  palette:
    scheme: leidenuniv
    primary: white
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
  font:
    text: Open Sans
    code: Ubuntu

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - abbr
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes

nav:
  - Home: index.md
  - Getting started:
    - Introduction: introduction.md
    - Requirements: requirements.md
    - Installation: installation.md
    - Customization: customization.md
    - Technical notes: technical-notes.md
    - Troubleshooting: troubleshooting.md
    - Data privacy: data-privacy.md
    - License: license.md

  - More info:
    - About us: about.md

  - Changelog:
    - Alma-Primo Locate Tool: changelog.md

copyright: GNU General Public License v3.0 - Leiden University Libraries

## Social Media
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://www.universiteitleiden.nl
    - icon: fontawesome/brands/github-alt
      link: https://github.com/LeidenUniversityLibrary
